   
function RotationMatrix = eulerAngle_2_rotationMatrix(EulerAngles)

    R_X = [1 0 0; ...
    0 cos(EulerAngles(1)) -sin(EulerAngles(1)); ...
    0 sin(EulerAngles(1)) cos(EulerAngles(1))];

    R_Y = [cos(EulerAngles(2)) 0 sin(EulerAngles(2)); ...
    0 1 0; ...
    -sin(EulerAngles(2)) 0 cos(EulerAngles(2))];

    R_Z = [cos(EulerAngles(3)) -sin(EulerAngles(3)) 0; ...
    sin(EulerAngles(3)) cos(EulerAngles(3)) 0; ...
    0 0 1];

    RotationMatrix = R_X*R_Y*R_Z;

end